#!/usr/bin/env bash
set -euo pipefail

AUTOSTART_CONFIG_FILE="${AUTOSTART_CONFIG_FILE:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/autostart_config.env}"

if [[ -f "$AUTOSTART_CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$AUTOSTART_CONFIG_FILE"
fi

AUTOSTART_USER="${AUTOSTART_USER:-$(id -un)}"
AUTOSTART_GROUP="${AUTOSTART_GROUP:-$(id -gn "$AUTOSTART_USER" 2>/dev/null || id -gn)}"
AUTOSTART_HOME="${AUTOSTART_HOME:-$(getent passwd "$AUTOSTART_USER" | cut -d: -f6)}"
AUTOSTART_HOME="${AUTOSTART_HOME:-$HOME}"
AUTOSTART_DIR="${AUTOSTART_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
AUTOSTART_UID="${AUTOSTART_UID:-$(id -u "$AUTOSTART_USER" 2>/dev/null || id -u)}"
AUTOSTART_CONDA_BIN="${AUTOSTART_CONDA_BIN:-}"
AUTOSTART_HIDDIFY_APPIMAGE="${AUTOSTART_HIDDIFY_APPIMAGE:-$AUTOSTART_HOME/Downloads/Hiddify-Linux-x64.AppImage}"
AUTOSTART_XAUTHORITY="${AUTOSTART_XAUTHORITY:-$AUTOSTART_HOME/.Xauthority}"
AUTOSTART_XDG_RUNTIME_DIR="${AUTOSTART_XDG_RUNTIME_DIR:-/run/user/$AUTOSTART_UID}"
AUTOSTART_DBUS_SESSION_BUS_ADDRESS="${AUTOSTART_DBUS_SESSION_BUS_ADDRESS:-unix:path=$AUTOSTART_XDG_RUNTIME_DIR/bus}"

export AUTOSTART_USER AUTOSTART_GROUP AUTOSTART_HOME AUTOSTART_DIR AUTOSTART_UID
export AUTOSTART_CONDA_BIN AUTOSTART_HIDDIFY_APPIMAGE AUTOSTART_XAUTHORITY
export AUTOSTART_XDG_RUNTIME_DIR AUTOSTART_DBUS_SESSION_BUS_ADDRESS
